import { Providers } from "@/components/ui/providers";
import NavBar from "./navbar.js";
import Footer from "./footer.js";

import type { Metadata } from "next";
import { Birthstone_Bounce, Frank_Ruhl_Libre } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
